config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only:[:new, :create, :destroy]

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy' # Manual uses:- match 'signout', to: 'sessions#destroy' via: :delete (position 9558)

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Check out Rubular to test REGEX expressions at http://rubular.com/


class User < ActiveRecord::Base
  #attr_accessible :name, :email, :password, :password_confirmation # Deprecated. This is now done in the controller
  has_secure_password

  before_save {|user| user.email = email.downcase}  # Position 7434
  # before_save{self.email.downcase!} # Another way of checking Position 7948
  before_save :create_remember_token

  validates(:name, presence: true, length:{maximum: 50})
  VALID_EMAIL_REGEX = /\A[\w +\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, format:{with: VALID_EMAIL_REGEX}, uniqueness:{case_sensitive: false}) #Position 7316 for validations
  validates(:password, presence: true, length:{minimum: 6})
  validates(:password_confirmation, presence: true)

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions/new
  def new

  end

  # POST /sessions
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the users show page
      sign_in user
      redirect_to user
    else
      # Create an error message and re-render the Sign in page
      flash.now[:error] = 'Invalid password/email combination'
      render 'new'
    end
  end

  #DELETE /sessions/:id
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show]

  # GET /users/1
  def show
    # set_user #Not required as called in the before_action above
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/:id
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # This 'permit' code replaces the deprecated attr_accessible in the model
  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    redirect_to signin_path, notice: 'Sign in.' unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    @current_user == user
  end

  def sign_out
    self.current_user?(nil)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Return the Gravatar for the given user from http://gravatar.com position 8375
  # Gravatar Login P - tr34cl3t4rt
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png" # This works
    #gravatar_url = "https://secure.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50.png" # This URL came from the tech notes at https://secure.gravatar.com/site/implement/images/
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small><a href='http://railstutorial.org/'>Rails Tutorial</a>by Paul Wagstaff</small>
  <nav>
    <ul class='nav-pills pull-right'>
      <li><%= link_to 'About', about_path%></li>
      <li><%= link_to 'Contact', contact_path%></li>
      <li><a href='http://www.bbc.co.uk/sport'>News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!-- This is called a 'Partial' and must be named with a leading underscore -->
<!-- Partials are called like this:- render 'layouts/footer' -->
<nav class='navbar navbar-inverse navbar-fixed-top'>
    <div class='container-fluid'>
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#myNavbar'>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
            <%= link_to 'Sample App', '/', class: 'navbar-brand'%>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class='navbar-nav navbar-right'>
                <li><a class='navbar-brand' href='/'><span class='glyphicon glyphicon-home'></span> Home</a></li>
                <li><a class='navbar-brand' href='/help'><span class='glyphicon glyphicon-info-sign'></span> Help</a></li>
                <% if signed_in? %>
                    <li><%= link_to 'Users', '#', class: 'navbar-brand' %></li>
                    <li id='fat-menu' class='dropdown'><a href ='#' class='dropdown-toggle navbar-brand' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Account<b class='caret'></b></a>
                    <ul class='dropdown-menu'>
                        <li><%= link_to 'Profile', current_user %></li>
                        <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                        <li class='divider'></li>
                        <li><%= link_to 'Sign out', signout_path, method: 'delete'%></li>
                    </ul>
                    </li>
                <% else %>
                    <li><a class='navbar-brand' href='signin'><span class='glyphicon glyphicon-log-in'></span> Sign In</a></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[ if lt IE 9]>
 <script src ="http://html5shim.googlecode.com/svn/trunk/html5.js">
 </script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title( yield(:title))%></title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags%>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render 'layouts/shim' %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do | key, value | %>
      <div class =" alert alert-<%= key %>" > <%= value %>
      </div>
  <% end %>
  <%= yield%>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development?%>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id ="error_explanation">
      <div class ="alert alert-error">The form contains <%= pluralize(@user.errors.count, 'error')%>.</div>
      <ul>
        <% @user.errors.full_messages.each do | msg | %>
            <li>* <%= msg%></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>This is the about page for the <a href="http:// railstutorial.org/"> Ruby on Rails Tutorial</a>sample application.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<h1>Contact Us</h1>
<p>This is the contact page for the <a href="http:// railstutorial.org/"> Ruby on Rails Tutorial</a>sample application.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>This is the help page for the <a href="http:// railstutorial.org/"> Ruby on Rails Tutorial</a>sample application.</p>

app/views/static_pages/home.html.erb
<div class='center hero-unit'>
<h1>Welcome to the Sample App</h1>
  <h2>This is the home page for the <a href='http://railstutorial.org/'>Ruby on Rails Tutorial</a> sample application.</h2>
  <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary'%></div>
  <%= link_to image_tag('Boofle1.png', alt: 'Rails'), 'http://rubyonrails.org/'%>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class ='row'>
    <%= form_for(@user) do | f |%>
    <%= render 'shared/error_messages'%>
    <div class='col-md-4 col-md-offset-4'><%= f.label :name%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.text_field :name%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.label :email%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.text_field :email%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.label :password%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.password_field :password%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.label :password_confirmation, 'Confirmation'%></div>
    <div class='col-md-4 col-md-offset-4'><%= f.password_field :password_confirmation%></div>
    <div class='col-md-2 col-md-offset-5'><%= f.submit 'Save changes', class: 'btn btn-lg btn-primary'%></div>
    <% end %>
</div>
<div class ='row'><br /></div>
<div class='panel panel-info col-md-6 col-md-offset-3'>
  <div class='panel-heading'>Gravatar Image</div>
  <div class='panel-content'>
      <div class ='row'>
        <div class='col-md-offset-2'><%= gravatar_for @user%>
         <a href='http://gravatar.com/emails'>Change</a></div>
      </div>
  </div>
</div>
<div class ='row'><br /></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class ='row'>
  <div class ='span12'>
    <%= form_for(@user) do | f |%>
        <%= render 'shared/error_messages'%>
        <div class='col-md-4 col-md-offset-4'><%= f.label :name%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.text_field :name%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.label :email%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.text_field :email%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.label :password%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.password_field :password%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.label :password_confirmation, 'Confirmation'%></div>
        <div class='col-md-4 col-md-offset-4'><%= f.password_field :password_confirmation%></div>
        <div class='col-md-2 col-md-offset-5'><%= f.submit 'Create account', class: 'btn btn-lg btn-primary'%></div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%provide(:title, @user.name)%>

<div class ="row">
  <aside class ="span4">
    <section>
      <h1>
        <%= gravatar_for(@user)%>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>